spring:

# H2
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
  datasource:
    url: jdbc:h2:file:~/organizationdb
    username: sa
    driver-class-name: org.h2.Driver
    platform: h2

# Service discovery
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
